### ISSUE TITLE
chore: Add pre-commit hooks with Lefthook

### ISSUE THREAD

**Issue by malpou** [MetsaApp/meos-graphics#21]
## Description
Add pre-commit hooks using lefthook to run the same checks locally that our CI (Test) workflow runs in GitHub Actions. This will catch issues before they're pushed to the repository. Lefthook is a Go-friendly git hooks manager that works well with Go projects.

### Pre-commit Checks
The hooks should run the same checks as our GitHub Actions Test workflow:
1. **Build**: Ensure code compiles
2. **Test**: Run all unit tests
3. **Lint**: Run golangci-lint
4. **Documentation Generation**: Ensure docs are up-to-date (once implemented)

### Implementation Using Lefthook
1. **Install lefthook**:
```bash
# Install globally
go install github.com/evilmartians/lefthook@latest

# Or add to project tools
go get github.com/evilmartians/lefthook
```

2. **Configure pre-commit hooks** in `.lefthook.yml`:
```yaml
# .lefthook.yml
pre-commit:
  parallel: true
  commands:
    build:
      run: go build ./...
      tags: build code
      
    test:
      run: go test ./...
      tags: test
      
    lint:
      run: golangci-lint run
      tags: lint
      
    docs-check:
      run:  < /dev/null | 
        if [ -f "Makefile" ] && grep -q "docs:" Makefile; then
          make docs && git diff --exit-code docs/
        fi
      tags: documentation
      skip:
        - merge
        - rebase

# Optional: pre-push hooks for more thorough checks
pre-push:
  parallel: true
  commands:
    test-coverage:
      run: go test -race -coverprofile=coverage.out ./...
      tags: test coverage
```

3. **Make hooks fast**:
   - Run checks in parallel (already configured)
   - Skip documentation check on merge/rebase
   - Use tags to run specific checks only

### CI Parity
Ensure hooks match GitHub Actions workflow:
```yaml
# Current .github/workflows/test.yml checks
- go build
- go test
- golangci-lint
- (future) documentation generation
```

### Developer Experience
1. **Easy setup**:
```bash
# Install lefthook in the project
lefthook install

# Run checks manually
lefthook run pre-commit

# Run specific checks by tag
lefthook run pre-commit --tags lint
```

2. **Clear output**: Lefthook provides colored, organized output
3. **Fast feedback**: Parallel execution, fail fast
4. **Skip option**: Use `--no-verify` or `LEFTHOOK=0`

### Setup Instructions
Add to README:
```bash
# Install lefthook
go install github.com/evilmartians/lefthook@latest

# Install git hooks
lefthook install

# Run checks manually
lefthook run pre-commit

# Commit with skipping hooks (use sparingly)
git commit --no-verify
# or
LEFTHOOK=0 git commit
```

### Project Files
1. **`.lefthook.yml`**: Hook configuration
2. **`.gitignore`**: Add `.lefthook-local.yml` for personal overrides
3. **`Makefile`**: Add targets for hook management
```makefile
.PHONY: install-hooks
install-hooks:
	@lefthook install

.PHONY: run-hooks
run-hooks:
	@lefthook run pre-commit
```

## Benefits
- Go-native tool, no Node.js dependency
- Fast parallel execution
- Flexible configuration with tags
- Good Windows support
- Can run hooks manually
- Supports local overrides

## Why Lefthook over Alternatives
1. **Git hooks directly**: Too manual, hard to maintain
2. **pre-commit framework**: Python-based, adds dependency
3. **husky**: Node.js dependency, not Go-native
4. **lefthook**: ✅ Go-native, fast, flexible

## Acceptance Criteria
- [ ] Lefthook installed and configured
- [ ] `.lefthook.yml` added with all checks
- [ ] Hooks run: build, test, lint
- [ ] Documentation check prepared (ready when docs generation is added)
- [ ] Installation documented in README
- [ ] Makefile targets added for convenience
- [ ] Hooks are fast (<30 seconds typical)
- [ ] Clear error messages on failure
- [ ] Can bypass with --no-verify or LEFTHOOK=0
- [ ] Works on all dev platforms (Linux/Mac/Windows)
- [ ] Added `.lefthook-local.yml` to .gitignore
